- name: Install System Packages 1 (base-devel, cmake, pkg-config, pthread)
  become: true
  pacman:
    name: [ "base", "base-devel", "linux", "linux-firmware", "nano", "dhcpcd", "net-tools", "grub", "cmake", "pkg-config", "systemd", "gnupg", "pacman-contrib" ]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, gettext)
  become: true
  pacman:
    name: [ "lua51", "unzip", "libtool", "gettext", "jdk-openjdk"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  pacman:
    name: [
      "git",
      "i3blocks",
      "picom",
      "arc-gtk-theme",
      "lxappearance",
      "arandr",
      "feh",
      "playerctl",
      "picom",
      "curl",
      "htop",
      "go",
      "lsof",
      "i3-wm",
      "ccache",
      "ninja",
      "python-pip",
      "dconf-editor",
      "nvidia-settings",
      "pavucontrol",
      "moreutils",
      "clang",
      "mate",
      "alsa-lib",
      "libudev0-shim",
      "xorg",
      "xorg-server",
      "pulseaudio",
      "pulseaudio-alsa",
      "plasma",
      "kde-applications",
      "xdg-user-dirs",
      "ttf-freefont",
      "dmenu",
      "lightdm",
      "lightdm-gtk-greeter",
      "vlc",
      "firefox",
      "konsole",
      "gtkmm",
      "xf86-input-vmmouse",
      "xf86-video-vmware", 
      "open-vm-tools",
      "chromium"]
  tags:
    - install
    - core
    
- name: Download yay
  become: false
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: '/tmp/yay'
  tags:
    - install
    - core

- name: Build and install yay
  become: false
  shell: makepkg -si --noconfirm
  args:
    chdir: '/tmp/yay'
    creates: '/usr/bin/yay'
  tags:
    - install
    - core

- name: Install libpthread-stubs from AUR
  become: false
  shell: yay -S --noconfirm libpthread-stubs
  tags:
    - install
    - core
