- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
    version: release-0.9
  tags:
    - install
    - neovim
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - install
    - neovim
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - neovim
- name: Neovim Plugin Development 1
  become: true
  pacman: name=luarocks
  tags:
    - install
    - neovim
- name: Neovim Plugin Development 2 luacheck
  become: true
  shell: luarocks install luacheck
  tags:
    - install
    - neovim

- name: Install Packer
  shell: git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
  args:
    creates: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
  tags:
    - install
    - dotfiles
    - neovim

