- name: Install packages
  become: true
  pacman:
    name: [ "tmux", "wireshark-qt", "fzf", "kdenlive", "gimp", "xclip", "screenkey", "tldr", "ripgrep", "shutter", "firefox" ]
  tags:
    - install
    - productivity

- name: Install SDKMAN
  shell: curl -s "https://get.sdkman.io" | bash
  tags:
    - install
    - dotfiles
    - neovim
